name: Build Portable EXE

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Ultimate-Video-Player
          path: dist/*.exe
